import type { NodeAddress } from "@peerkit/api";
import type { IAuthoredDataSyncStore } from "@peerkit/api/authored-data-pull";
import { PeerkitNodeBuilder, type PeerkitNode } from "@peerkit/peerkit";
import { MemoryAgentKeyStore } from "@peerkit/test-utils";
import {
  AuthoredDataSync,
  FullReplicationStrategy,
  MemoryBlobStore,
} from "../src/index.js";

export interface TestNode {
  dataSync: AuthoredDataSync;
  store: IAuthoredDataSyncStore;
  node: PeerkitNode;
  nodeAddresses: NodeAddress[];
  shutDown: () => Promise<void>;
}

/**
 * Creates a test node wired with a DataSync instance via PeerkitNodeBuilder.
 *
 * Agent identity is generated by the builder's key pair.
 */
export async function createTestNode(opts: {
  id: string;
  pullIntervalMs?: number;
}): Promise<TestNode> {
  const store = new MemoryBlobStore();
  const dataSync = new AuthoredDataSync(
    store,
    new FullReplicationStrategy(),
    opts.pullIntervalMs ?? 5000,
  );

  // Listen on WebRTC Direct so the node is directly dialable on loopback.
  const listenAddr = "/ip4/127.0.0.1/udp/0/webrtc-direct";

  const node = await new PeerkitNodeBuilder({
    agentKeyStore: new MemoryAgentKeyStore(),
    networkAccessHandler: async () => true,
    messageHandler: async () => {},
  })
    .withId(opts.id)
    .withAddresses([listenAddr])
    .withNetworkAccessBytes(new Uint8Array([0]))
    .withModule(dataSync)
    .build();

  // The dialable address carries the ephemeral certhash, known only after
  // start, so read it from the running transport.
  const addresses = node.transport.getListenAddresses();
  const nodeAddress = addresses.find((a) => a.includes("/webrtc-direct"));
  if (nodeAddress === undefined) {
    throw new Error(
      `createTestNode: node has no webrtc-direct address; got: ${addresses.join(", ")}`,
    );
  }

  return {
    dataSync,
    store,
    node,
    nodeAddresses: [nodeAddress],
    shutDown: () => node.shutDown(),
  };
}
