import type { NodeAddress } from "@peerkit/api";
import { IAuthoredDataSyncStore } from "@peerkit/api/authored-data-sync";
import { PeerkitNodeBuilder, type PeerkitNode } from "@peerkit/peerkit";
import { MemoryAgentKeyStore } from "@peerkit/test-utils";
import getPort, { portNumbers } from "get-port";
import {
  AuthoredDataSync,
  FullReplicationStrategy,
  MemoryBlobStore,
} from "../src/index.js";

export interface TestNode {
  dataSync: AuthoredDataSync;
  store: IAuthoredDataSyncStore;
  node: PeerkitNode;
  nodeAddresses: NodeAddress[];
  shutDown: () => Promise<void>;
}

/**
 * Creates a test node wired with a DataSync instance via PeerkitNodeBuilder.
 *
 * Agent identity is generated by the builder's key pair.
 */
export async function createTestNode(opts: {
  id: string;
  pullIntervalMs?: number;
}): Promise<TestNode> {
  const store = new MemoryBlobStore();
  const dataSync = new AuthoredDataSync(
    store,
    new FullReplicationStrategy(),
    opts.pullIntervalMs ?? 5000,
  );

  const port = await getPort({ port: portNumbers(30_000, 40_000) });
  const addresses = [`/ip4/0.0.0.0/tcp/${port}/ws`];

  const node = await new PeerkitNodeBuilder({
    agentKeyStore: new MemoryAgentKeyStore(),
    networkAccessHandler: async () => true,
    messageHandler: async () => {},
  })
    .withId(opts.id)
    .withAddresses(addresses)
    .withNetworkAccessBytes(new Uint8Array([0]))
    .withModule(dataSync)
    .build();

  return {
    dataSync,
    store,
    node,
    nodeAddresses: addresses,
    shutDown: () => node.shutDown(),
  };
}
