import {
  configure,
  getAnsiColorFormatter,
  getConsoleSink,
} from "@logtape/logtape";
import type { NodeAddress } from "@peerkit/api";
import { PeerkitNodeBuilder, type PeerkitNode } from "@peerkit/peerkit";
import getPort, { portNumbers } from "get-port";
import {
  AuthoredDataSync,
  FullReplicationStrategy,
  MemoryBlobStore,
} from "../src/index.js";
import { IAuthoredDataSyncStore } from "../src/types/store.js";

export const setupTestLogger = async () => {
  await configure({
    sinks: {
      console: getConsoleSink({
        formatter: getAnsiColorFormatter({
          format({ timestamp, level, category, message, record }) {
            let output = `${timestamp} ${level} ${category}`;
            if (typeof record.properties["id"] === "string") {
              output = output + ` ${record.properties["id"]}`;
            }
            output = output + `: ${message}`;
            return output;
          },
        }),
      }),
    },
    loggers: [
      {
        category: "peerkit",
        lowestLevel: "info",
        sinks: ["console"],
      },
    ],
  });
};

export interface TestNode {
  dataSync: AuthoredDataSync;
  store: IAuthoredDataSyncStore;
  node: PeerkitNode;
  nodeAddress: NodeAddress;
  shutDown: () => Promise<void>;
}

/**
 * Creates a test node wired with a DataSync instance via PeerkitNodeBuilder.
 *
 * Agent identity is generated by the builder's key pair.
 */
export async function createTestNode(opts: {
  id: string;
  pullIntervalMs?: number;
}): Promise<TestNode> {
  const store = new MemoryBlobStore();
  const dataSync = new AuthoredDataSync(
    store,
    new FullReplicationStrategy(),
    opts.pullIntervalMs ?? 5000,
  );

  const port = await getPort({ port: portNumbers(30_000, 40_000) });
  const address = `/ip4/0.0.0.0/tcp/${port}/ws`;

  const node = await new PeerkitNodeBuilder({
    networkAccessHandler: async () => true,
    messageHandler: async () => {},
  })
    .withId(opts.id)
    .withAddresses([address])
    .withNetworkAccessBytes(new Uint8Array([0]))
    .withModule(dataSync)
    .build();

  return {
    dataSync,
    store,
    node,
    nodeAddress: address,
    shutDown: () => node.shutDown(),
  };
}
