import type { NodeAddress } from "@peerkit/api";
import { IAuthoredDataSyncStore } from "@peerkit/api/authored-data-sync";
import { MemoryBlobStore } from "@peerkit/authored-data-sync";
import { PeerkitNodeBuilder, type PeerkitNode } from "@peerkit/peerkit";
import getPort, { portNumbers } from "get-port";
import { AuthoredDataPush, FullReplicationPolicy } from "../src/index.js";

export interface TestNode {
  push: AuthoredDataPush;
  store: IAuthoredDataSyncStore;
  node: PeerkitNode;
  nodeAddress: NodeAddress;
  shutDown: () => Promise<void>;
}

/**
 * Creates a test node wired with an AuthoredDataPush instance via
 * PeerkitNodeBuilder. Agent identity is generated by the builder's key pair.
 */
export async function createTestNode(opts: { id: string }): Promise<TestNode> {
  const store = new MemoryBlobStore(new FullReplicationPolicy());
  const push = new AuthoredDataPush(store);

  const port = await getPort({ port: portNumbers(30_000, 40_000) });
  const address = `/ip4/0.0.0.0/tcp/${port}/ws`;

  const node = await new PeerkitNodeBuilder({
    networkAccessHandler: async () => true,
    messageHandler: async () => {},
  })
    .withId(opts.id)
    .withAddresses([address])
    .withNetworkAccessBytes(new Uint8Array([0]))
    .withModule(push)
    .build();

  return {
    push,
    store,
    node,
    nodeAddress: address,
    shutDown: () => node.shutDown(),
  };
}
