import type { NodeAddress } from "@peerkit/api";
import { IAuthoredDataSyncStore } from "@peerkit/api/authored-data-pull";
import { MemoryBlobStore } from "@peerkit/data-store";
import { PeerkitNodeBuilder, type PeerkitNode } from "@peerkit/peerkit";
import { MemoryAgentKeyStore } from "@peerkit/test-utils";
import { AuthoredDataPush } from "../src/index.js";

export interface TestNode {
  push: AuthoredDataPush;
  store: IAuthoredDataSyncStore;
  node: PeerkitNode;
  nodeAddress: NodeAddress;
  shutDown: () => Promise<void>;
}

/**
 * Creates a test node wired with an AuthoredDataPush instance via
 * PeerkitNodeBuilder. Agent identity is generated by the builder's key pair.
 */
export async function createTestNode(opts: { id: string }): Promise<TestNode> {
  const store = new MemoryBlobStore();
  const push = new AuthoredDataPush(store);

  // Listen on WebRTC Direct so the node is directly dialable on loopback.
  const listenAddr = "/ip4/127.0.0.1/udp/0/webrtc-direct";

  const node = await new PeerkitNodeBuilder({
    agentKeyStore: new MemoryAgentKeyStore(),
    networkAccessHandler: async () => true,
    messageHandler: async () => {},
  })
    .withId(opts.id)
    .withAddresses([listenAddr])
    .withNetworkAccessBytes(new Uint8Array([0]))
    .withModule(push)
    .build();

  // The dialable address carries the ephemeral certhash, known only after
  // start, so read it from the running transport.
  const addresses = node.transport.getListenAddresses();
  const nodeAddress = addresses.find((a) => a.includes("/webrtc-direct"));
  if (nodeAddress === undefined) {
    throw new Error(
      `createTestNode: node has no webrtc-direct address; got: ${addresses.join(", ")}`,
    );
  }

  return {
    push,
    store,
    node,
    nodeAddress,
    shutDown: () => node.shutDown(),
  };
}
